my_django_project/urls.py
from django.contrib import admin
from django.urls import path, include

app_name = 'form'

urlpatterns = [
    path('', include('web_form.urls')),
    path('captcha/', include('captcha.urls')),
    path('admin/', admin.site.urls),
]

web_form/urls.py
from django.urls import path

from . import views

app_name = 'forms'

urlpatterns = [
    path('', views.list_articles_view, name='list_articles_view'),
    path('article_create/', views.article_create, name='article_create'),
    path('<int:article_id>/', views.article_view, name='article_view'),
]

web_form/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=30, verbose_name='Заголовок статьи')
    user_name = models.CharField(max_length=30, verbose_name='Имя пользователя')
    text = models.TextField(verbose_name='Текст')
    date_send = models.DateField(auto_now=True)

    def __str__(self):
        return self.title

web_form/forms.py
from django import forms
from captcha.fields import CaptchaField

from .models import Article


class ArticleForm(forms.ModelForm):
    captcha = CaptchaField(label='Докажи что не робот ')

    class Meta:
        model = Article
        fields = '__all__'

web_form/views.py
from django.shortcuts import render
from django.http import HttpResponse, Http404

from .forms import ArticleForm
from .models import Article


def list_articles_view(request):
    articles_qs = Article.objects.all()
    return render(request, 'web_form/list.html', {'list': articles_qs})


def article_create(request):
    form = ArticleForm(request.POST or None)
    reset = False

    if request.method == "POST":
        if form.is_valid():
            #form.save()
            return HttpResponse(f"Сообщение {form['user_name'].value()} отправленно!")
        reset = True

    return render(request, 'web_form/create.html', {'form': form, 'reset': reset})


def article_view(request, article_id):
    try:
        article = Article.objects.get(id=article_id)
    except Article.DoesNotExist:
        raise Http404("Статья не найденна!")

    return render(request, 'web_form/form.html', {'form': article})

web_form/templates/main_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF8">
    <title>Form</title>

    <link rel="stylesheet" href="/static/css/bootstrap.min.css" type="text/css">
</head>
<body class="jumbotron">

{% block content %}

{% endblock %}

</body>
</html>

web_form/templates/web_form/create.html
{% extends "main_page.html" %}

{% block content %}

<form method="post">
    {% csrf_token %}
    <h3>{{form.title.label}}</h3>
    <h5>{{form.title}}</h5>
    <h3>{{form.user_name.label}}</h3>
    <h5>{{form.user_name}}</h5>
    <h3>{{form.text.label}}</h3>
    {{form.text}}
    <hr>
    {{form.captcha}}
    <br>
    <input type="submit" value="Отправить сообщение">
    {% if reset %}
        <br>
        <b>Ошибка ввода капчи, вы робот!</b>
    {% endif %}
</form>
<hr>
<form action = "{% url 'forms:list_articles_view' %}">
    <input type="submit" value="На главную">
</form>

{% endblock %}

web_form/templates/web_form/form.html
{% extends "main_page.html" %}

{% block content %}

<h3>{{form.title}}</h3>
<hr>
<h5>{{form.user_name}}</h5>
<h5>{{form.date_send}}</h5>
<br>
{{form.text}}
<hr>
<form action = "{% url 'forms:list_articles_view' %}">
    <input type="submit" value="На главную">
</form>

{% endblock %}

web_form/templates/web_form/list.html
{% extends "main_page.html" %}

{% block content %}

<h2>Список сообщений</h2>
<hr>
{% for form in list %}
    <h2>Автор : {{form.user_name}}</h2>
    <a href="{% url 'forms:article_view' form.id%}"><h4>{{form.title}}</h4> </a>
{% endfor %}
<hr>
<form action = "{% url 'forms:article_create' %}">
    <input type="submit" value="Добавить сообщение">
</form>
{% endblock %}